services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3307"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=pickpaydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
      
  volumes:
    db_data: